services:

  db:
    image: mysql:8.0
    container_name: file_manager
    cap_add:
      - SYS_NICE
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-file_manager}
      MYSQL_USER: ${DB_USERNAME:-file_manager}
      MYSQL_PASSWORD: ${DB_PASSWORD:-file_manager}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: file_manager_minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: file_manager_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: file_manager_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: file_manager_test
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:
  minio_data:
  redis_data:

networks:
  app-network:
    driver: bridge
